title: Jason La Product Manager
author: GitHub User - jasonduro
email: product@jasonlamanque.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my new site. You can learn more about more work experience here. I've provided more details than what can fit on a CV or cover letter
  so that you have more context into what I've experienced and accomplished. 

# social links
twitter_username: @jasonlamanque
github_username:  jasonduro

show_excerpts: true # set to false to remove excerpts on the homepage
